plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'io.freefair.lombok' version '9.2.0'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version + "+" + minecraft_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { // JEI
        url "https://maven.blamejared.com/"
    }
    maven { // Jade
        url "https://api.modrinth.com/maven"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    compileOnly("org.jspecify:jspecify:1.0.0")
    compileOnly("org.jetbrains:annotations:26.0.2")
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")

    compileOnly("mezz.jei:jei-26.1.2-fabric-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-26.1.2-fabric:${jei_version}")

    implementation "maven.modrinth:jade:${jade_version}"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            loader_version         : loader_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            groupId = project.mod_group_id
            artifactId = project.mod_id
            version = project.version
        }
    }
    repositories {
        maven {
            name = 'reposilite'

            def isSnapshot = project.version.toString().endsWith('-SNAPSHOT')
            def repoUrl = isSnapshot ? 'https://maven.satherov.dev/snapshots' : 'https://maven.satherov.dev/releases'

            url = uri(repoUrl)

            credentials {
                username = System.getenv('REPOSILITE_USERNAME')
                password = System.getenv('REPOSILITE_TOKEN')
            }

            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
